use serde::{Serialize, Deserialize};
use std::fs::File;
use std::io::Write;
use crate::metadata::PhotoMetadata;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ExportRecord {
    pub file_path: String,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
    pub altitude: Option<f64>,
    pub timestamp: Option<String>,
    pub address: Option<String>,
    pub device: Option<String>,
    pub model: Option<String>,
}

impl ExportRecord {
    pub fn from_meta(path: &str, meta: &PhotoMetadata, address: Option<String>) -> Self {
        Self {
            file_path: path.to_string(),
            latitude: meta.latitude,
            longitude: meta.longitude,
            altitude: meta.altitude,
            timestamp: meta.timestamp.clone(),
            address,
            device: meta.make.clone(),
            model: meta.model.clone(),
        }
    }
}

pub fn save_to_json(records: &[ExportRecord], path: &str) -> std::io::Result<()> {
    let json = serde_json::to_string_pretty(records)?;
    let mut file = File::create(path)?;
    file.write_all(json.as_bytes())?;
    Ok(())
}

pub fn save_to_csv(records: &[ExportRecord], path: &str) -> Result<(), Box<dyn std::error::Error>> {
    let mut wtr = csv::Writer::from_path(path)?;
    
    // Header is automatically generated by Serialize
    for record in records {
        wtr.serialize(record)?;
    }
    
    wtr.flush()?;
    Ok(())
}
